In [14]:
from transformers import AutoTokenizer

In [15]:
model = 'openai/gpt-oss-20b'

tokenizer = AutoTokenizer.from_pretrained(model)

raw_input = [
    "Learning about tokenizers is fun",
    "I don't like OOM errors"
]

inp = tokenizer(raw_input, padding=True, truncation=True, return_tensors='pt')
inp

Asking to truncate to max_length but no maximum length is provided and the model has no predefined maximum length. Default to no truncation.


{'input_ids': tensor([[54609,  1078,  6602, 24223,   382,  2827],
        [   40,  4128,  1299,   532,  2760, 10664]]), 'attention_mask': tensor([[1, 1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1, 1]])}

In [20]:
inp[0]

Encoding(num_tokens=6, attributes=[ids, type_ids, tokens, offsets, attention_mask, special_tokens_mask, overflowing])

In [22]:
inp = tokenizer("what is today's date?")
print(inp)
print(tokenizer.decode(inp['input_ids']))

{'input_ids': [13347, 382, 41482, 3521, 30], 'attention_mask': [1, 1, 1, 1, 1]}
what is today's date?


In [4]:
## Download pretrained model
# *Model (retrieve the hidden states)
# *ForCausalLM
# *ForMaskedLM
# *ForMultipleChoice
# *ForQuestionAnswering
# *ForSequenceClassification
# *ForTokenClassification

In [5]:
from transformers import AutoModel

In [6]:
model_card = 'openai/gpt-oss-20b'

model = AutoModel.from_pretrained(model_card, device_map='auto')

Fetching 40 files:   0%|          | 0/40 [00:00<?, ?it/s]

Loading checkpoint shards:   0%|          | 0/3 [00:00<?, ?it/s]

In [7]:
model

GptOssModel(
  (embed_tokens): Embedding(201088, 2880, padding_idx=199999)
  (layers): ModuleList(
    (0-23): 24 x GptOssDecoderLayer(
      (self_attn): GptOssAttention(
        (q_proj): Linear(in_features=2880, out_features=4096, bias=True)
        (k_proj): Linear(in_features=2880, out_features=512, bias=True)
        (v_proj): Linear(in_features=2880, out_features=512, bias=True)
        (o_proj): Linear(in_features=4096, out_features=2880, bias=True)
      )
      (mlp): GptOssMLP(
        (router): GptOssTopKRouter()
        (experts): Mxfp4GptOssExperts()
      )
      (input_layernorm): GptOssRMSNorm((2880,), eps=1e-05)
      (post_attention_layernorm): GptOssRMSNorm((2880,), eps=1e-05)
    )
  )
  (norm): GptOssRMSNorm((2880,), eps=1e-05)
  (rotary_emb): GptOssRotaryEmbedding()
)

In [11]:
out = model(**inp)
out

MoeModelOutputWithPast(last_hidden_state=tensor([[[ 1.2188e+00, -4.2500e+00,  4.1250e+00,  ..., -4.0312e+00,
           9.1250e+00, -1.8375e+01],
         [-5.1875e+00,  2.4219e+00, -1.4062e+00,  ..., -1.5469e+00,
           3.3203e-01, -1.9125e+01],
         [-8.5156e-01, -1.0703e+00,  3.8125e+00,  ...,  2.5312e+00,
           3.7188e+00, -1.9062e+00],
         [-1.5625e+00, -1.6406e+00,  3.0469e+00,  ...,  9.9219e-01,
           4.8750e+00, -1.1938e+01],
         [-8.8750e+00, -2.7148e-01, -8.4375e-01,  ..., -1.8203e+00,
           3.0312e+00,  4.0000e+00],
         [-5.4688e+00,  3.7305e-01,  3.0273e-01,  ..., -1.3281e+00,
          -1.0312e+00, -3.6250e+00]],

        [[-7.5625e+00, -3.0312e+00, -9.2578e-01,  ...,  9.6875e-01,
          -3.2344e+00, -3.4531e+00],
         [ 1.4562e+01,  4.6875e+00, -5.1953e-01,  ..., -2.6719e+00,
           2.4531e+00, -1.8281e+00],
         [-8.3125e+00,  2.9531e+00,  2.5781e+00,  ..., -4.1250e+00,
           1.9609e+00, -1.3625e+01],
         [-1

In [13]:
print(out.last_hidden_state.shape)
out.last_hidden_state

torch.Size([2, 6, 2880])


tensor([[[ 1.2188e+00, -4.2500e+00,  4.1250e+00,  ..., -4.0312e+00,
           9.1250e+00, -1.8375e+01],
         [-5.1875e+00,  2.4219e+00, -1.4062e+00,  ..., -1.5469e+00,
           3.3203e-01, -1.9125e+01],
         [-8.5156e-01, -1.0703e+00,  3.8125e+00,  ...,  2.5312e+00,
           3.7188e+00, -1.9062e+00],
         [-1.5625e+00, -1.6406e+00,  3.0469e+00,  ...,  9.9219e-01,
           4.8750e+00, -1.1938e+01],
         [-8.8750e+00, -2.7148e-01, -8.4375e-01,  ..., -1.8203e+00,
           3.0312e+00,  4.0000e+00],
         [-5.4688e+00,  3.7305e-01,  3.0273e-01,  ..., -1.3281e+00,
          -1.0312e+00, -3.6250e+00]],

        [[-7.5625e+00, -3.0312e+00, -9.2578e-01,  ...,  9.6875e-01,
          -3.2344e+00, -3.4531e+00],
         [ 1.4562e+01,  4.6875e+00, -5.1953e-01,  ..., -2.6719e+00,
           2.4531e+00, -1.8281e+00],
         [-8.3125e+00,  2.9531e+00,  2.5781e+00,  ..., -4.1250e+00,
           1.9609e+00, -1.3625e+01],
         [-1.2375e+01,  1.5137e-01,  1.1719e+00,  ...

In [16]:
out.keys()

odict_keys(['last_hidden_state', 'past_key_values'])

In [1]:
from transformers import AutoModelForSequenceClassification, AutoTokenizer

In [69]:
model_card = 'distilbert-base-uncased-finetuned-sst-2-english'

tok = AutoTokenizer.from_pretrained(model_card)

raw_input = [
    "Learning about tokenizers is fun",
    "I don't like OOM errors"
]

inp = tok(raw_input, padding=True, truncation=True, return_tensors='pt')
print(inp)

print(tok.decode(inp.input_ids[0]))
print(tok.decode(inp.input_ids[1]))

{'input_ids': tensor([[  101,  4083,  2055, 19204, 17629,  2015,  2003,  4569,   102,     0],
        [  101,  1045,  2123,  1005,  1056,  2066,  1051,  5358, 10697,   102]]), 'attention_mask': tensor([[1, 1, 1, 1, 1, 1, 1, 1, 1, 0],
        [1, 1, 1, 1, 1, 1, 1, 1, 1, 1]])}
[CLS] learning about tokenizers is fun [SEP] [PAD]
[CLS] i don't like oom errors [SEP]


In [3]:
model = AutoModelForSequenceClassification.from_pretrained('distilbert-base-uncased-finetuned-sst-2-english')

out = model(**inp)

model.safetensors:   0%|          | 0.00/268M [00:00<?, ?B/s]

In [4]:
# logits (raw unnormalized scores to be converted into probability)
out

SequenceClassifierOutput(loss=None, logits=tensor([[-4.2268,  4.5430],
        [ 2.5654, -2.1671]], grad_fn=<AddmmBackward0>), hidden_states=None, attentions=None)

In [7]:
import torch

pred = torch.nn.functional.softmax(out.logits, dim=-1)
pred

tensor([[1.5533e-04, 9.9984e-01],
        [9.9127e-01, 8.7273e-03]], grad_fn=<SoftmaxBackward0>)

In [8]:
model.config.id2label

{0: 'NEGATIVE', 1: 'POSITIVE'}

In [ ]:
# First sentence: NEGATIVE: 0.0402, POSITIVE: 0.9598
# Second sentence: NEGATIVE: 0.9995, POSITIVE: 0.0005

# Models

In [9]:
from transformers import AutoModel

model = AutoModel.from_pretrained("bert-base-cased")
model

config.json:   0%|          | 0.00/570 [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/436M [00:00<?, ?B/s]

BertModel(
  (embeddings): BertEmbeddings(
    (word_embeddings): Embedding(28996, 768, padding_idx=0)
    (position_embeddings): Embedding(512, 768)
    (token_type_embeddings): Embedding(2, 768)
    (LayerNorm): LayerNorm((768,), eps=1e-12, elementwise_affine=True)
    (dropout): Dropout(p=0.1, inplace=False)
  )
  (encoder): BertEncoder(
    (layer): ModuleList(
      (0-11): 12 x BertLayer(
        (attention): BertAttention(
          (self): BertSdpaSelfAttention(
            (query): Linear(in_features=768, out_features=768, bias=True)
            (key): Linear(in_features=768, out_features=768, bias=True)
            (value): Linear(in_features=768, out_features=768, bias=True)
            (dropout): Dropout(p=0.1, inplace=False)
          )
          (output): BertSelfOutput(
            (dense): Linear(in_features=768, out_features=768, bias=True)
            (LayerNorm): LayerNorm((768,), eps=1e-12, elementwise_affine=True)
            (dropout): Dropout(p=0.1, inplace=False

In [10]:
from transformers import BertModel

model = BertModel.from_pretrained("bert-base-cased")
model

BertModel(
  (embeddings): BertEmbeddings(
    (word_embeddings): Embedding(28996, 768, padding_idx=0)
    (position_embeddings): Embedding(512, 768)
    (token_type_embeddings): Embedding(2, 768)
    (LayerNorm): LayerNorm((768,), eps=1e-12, elementwise_affine=True)
    (dropout): Dropout(p=0.1, inplace=False)
  )
  (encoder): BertEncoder(
    (layer): ModuleList(
      (0-11): 12 x BertLayer(
        (attention): BertAttention(
          (self): BertSdpaSelfAttention(
            (query): Linear(in_features=768, out_features=768, bias=True)
            (key): Linear(in_features=768, out_features=768, bias=True)
            (value): Linear(in_features=768, out_features=768, bias=True)
            (dropout): Dropout(p=0.1, inplace=False)
          )
          (output): BertSelfOutput(
            (dense): Linear(in_features=768, out_features=768, bias=True)
            (LayerNorm): LayerNorm((768,), eps=1e-12, elementwise_affine=True)
            (dropout): Dropout(p=0.1, inplace=False

In [11]:
!pwd

/app/misc


huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
	- Avoid using `tokenizers` before the fork if possible
	- Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)


## saving model weights and arch config

In [12]:
## save model weights and architecture config

model.save_pretrained('/app/misc/model_card/model.pt')

## Multiple sequence

In [23]:
import torch 
from transformers import AutoTokenizer, AutoModelForSequenceClassification

In [27]:
model_weight = "distilbert-base-uncased-finetuned-sst-2-english"

tok = AutoTokenizer.from_pretrained(model_weight)
model = AutoModelForSequenceClassification.from_pretrained(model_weight)

sequence = "I've been waiting for this course my  whole life."

tokens = tok.tokenize(sequence)
print(tokens)
ids = tok.convert_tokens_to_ids(tokens)
print(ids)

## Batched input
input_ids = torch.tensor([ids, ids]) ## <---
print(input_ids)

out = model(input_ids)
print(out.logits)

['i', "'", 've', 'been', 'waiting', 'for', 'this', 'course', 'my', 'whole', 'life', '.']
[1045, 1005, 2310, 2042, 3403, 2005, 2023, 2607, 2026, 2878, 2166, 1012]
tensor([[1045, 1005, 2310, 2042, 3403, 2005, 2023, 2607, 2026, 2878, 2166, 1012],
        [1045, 1005, 2310, 2042, 3403, 2005, 2023, 2607, 2026, 2878, 2166, 1012]])
tensor([[-2.7220,  2.7847],
        [-2.7220,  2.7847]], grad_fn=<AddmmBackward0>)


In [33]:
## Padding (Manual)

batch = [[200,200,200], [200,200]]
print(batch)
padding_id = 100

batch[1].append(padding_id)
batch

[[200, 200, 200], [200, 200]]


[[200, 200, 200], [200, 200, 100]]

In [43]:
## Padding (tokenizer class value)
sequence1_ids = [[200,200,200]]
sequence2_ids = [[200,200]]
batch_ids = [
    [200,200,200], 
    [200,200]]
print(batch_ids)
batch_ids[1].append(tok.pad_token_id)
print(batch_ids)

[[200, 200, 200], [200, 200]]
[[200, 200, 200], [200, 200, 0]]


In [ ]:
## convert to tensor
seq1_tensor = torch.tensor(sequence1_ids)
seq2_tensor = torch.tensor(sequence2_ids)
batch_id_tensor = torch.tensor(batch_ids)
print(seq1_tensor.shape)
print(seq2_tensor.shape)
print(batch_id_tensor.shape)

In [49]:
## Run through classifier and output logits
print('sequence 1 logits:', model(seq1_tensor).logits)
print('sequence 2 logits:', model(seq2_tensor).logits)
print('batch sequence logits:', model(batch_id_tensor).logits)

sequence 1 logits: tensor([[ 1.5694, -1.3895]], grad_fn=<AddmmBackward0>)


We strongly recommend passing in an `attention_mask` since your input_ids may be padded. See https://huggingface.co/docs/transformers/troubleshooting#incorrect-output-when-padding-tokens-arent-masked.


sequence 2 logits: tensor([[ 0.5803, -0.4125]], grad_fn=<AddmmBackward0>)
batch sequence logits: tensor([[ 1.5694, -1.3895],
        [ 1.3374, -1.2163]], grad_fn=<AddmmBackward0>)


In [50]:
# padding value was used during self-attention. to ignroe the padding, must apply an attention mask

attention_mask = [[1,1,1], [1,1,0]]
print(attention_mask)

[[1, 1, 1], [1, 1, 0]]


In [51]:
model(batch_id_tensor, attention_mask=torch.tensor(attention_mask)).logits

tensor([[ 1.5694, -1.3895],
        [ 0.5803, -0.4125]], grad_fn=<AddmmBackward0>)

In [71]:
help(AutoTokenizer)

Help on class AutoTokenizer in module transformers.models.auto.tokenization_auto:

class AutoTokenizer(builtins.object)
 |  This is a generic tokenizer class that will be instantiated as one of the tokenizer classes of the library when
 |  created with the [`AutoTokenizer.from_pretrained`] class method.
 |
 |  This class cannot be instantiated directly using `__init__()` (throws an error).
 |
 |  Methods defined here:
 |
 |  __init__(self)
 |      Initialize self.  See help(type(self)) for accurate signature.
 |
 |  ----------------------------------------------------------------------
 |  Class methods defined here:
 |
 |  from_pretrained(pretrained_model_name_or_path, *inputs, **kwargs)
 |      Instantiate one of the tokenizer classes of the library from a pretrained model vocabulary.
 |
 |      The tokenizer class to instantiate is selected based on the `model_type` property of the config object (either
 |      passed as an argument or loaded from `pretrained_model_name_or_path` if 

## All together

In [81]:
################################ All together Now

In [1]:
sentence1 = "Today is going to be a good day."
sentence2 = "I hope everything works out in my favor!!"

## Tokenize
from transformers import AutoTokenizer, AutoModelForSequenceClassification

tokenizer = AutoTokenizer.from_pretrained("distilbert-base-uncased-finetuned-sst-2-english")
classifier = AutoModelForSequenceClassification.from_pretrained("distilbert-base-uncased-finetuned-sst-2-english")

message_batch = [sentence1, sentence2]
print(message_batch)

['Today is going to be a good day.', 'I hope everything works out in my favor!!']


In [3]:
## In one step tokenization to classification
import torch

batch_id = tokenizer(message_batch, padding=True,  return_tensors='pt') 
print(batch_id)

# out = classifier(batch_id.input_ids) # ALSD WORKS
out = classifier(**batch_id)
print('\n',out)

print('\nPrediction: \n',torch.nn.functional.softmax(out.logits, dim=-1))
print('\n',classifier.config.id2label)

{'input_ids': tensor([[ 101, 2651, 2003, 2183, 2000, 2022, 1037, 2204, 2154, 1012,  102,    0],
        [ 101, 1045, 3246, 2673, 2573, 2041, 1999, 2026, 5684,  999,  999,  102]]), 'attention_mask': tensor([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0],
        [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]])}

 SequenceClassifierOutput(loss=None, logits=tensor([[-4.2881,  4.7028],
        [-4.0785,  4.4558]], grad_fn=<AddmmBackward0>), hidden_states=None, attentions=None)

Prediction: 
 tensor([[1.2453e-04, 9.9988e-01],
        [1.9658e-04, 9.9980e-01]], grad_fn=<SoftmaxBackward0>)

 {0: 'NEGATIVE', 1: 'POSITIVE'}


In [4]:
## In multiple step tokenization to classification

print(len(tokenizer(sentence1).input_ids))
print(len(tokenizer(sentence2).input_ids))

print('sentence 1 tokens: \n',torch.tensor(tokenizer(sentence1).input_ids))
print('\nsentence 2 tokens: \n',torch.tensor(tokenizer(sentence2).input_ids))

tokenized_sentence1 = tokenizer(sentence1).input_ids
tokenized_sentence2 = tokenizer(sentence2).input_ids

tokenized_sentence1.append(tokenizer.pad_token_id)
print(len(tokenized_sentence1))
print(tokenized_sentence1,'\n')


batched = [tokenized_sentence1, tokenized_sentence2]
print('\nTokenized_batch: \n',batched)
print('\nTensor_batch: \n',torch.tensor(batched))


# Prediction
# print('Logits on sentence 1: ', classifier())
print('\nLogits on batch: \n',classifier(torch.tensor(batched)))

attn_mask = [[1,1,1,1,1,1,1,1,1,1,1,0],[1,1,1,1,1,1,1,1,1,1,1,1]]

print("\nsentence 1 logits \n", classifier(torch.tensor([tokenized_sentence1])).logits)
print('\nsentence 2 logits \n', classifier(torch.tensor([tokenized_sentence2])).logits)

print('\nBatched sentence 1 & 2 logite \n', classifier(torch.tensor(batched), attention_mask=torch.tensor(attn_mask))) # CAUSED RESULT TO BE DIFFERENT!!!

print('\nPredictions: ', torch.nn.functional.softmax(classifier(torch.tensor([tokenized_sentence1])).logits, dim=-1))
classifier.config.id2label

We strongly recommend passing in an `attention_mask` since your input_ids may be padded. See https://huggingface.co/docs/transformers/troubleshooting#incorrect-output-when-padding-tokens-arent-masked.


11
12
sentence 1 tokens: 
 tensor([ 101, 2651, 2003, 2183, 2000, 2022, 1037, 2204, 2154, 1012,  102])

sentence 2 tokens: 
 tensor([ 101, 1045, 3246, 2673, 2573, 2041, 1999, 2026, 5684,  999,  999,  102])
12
[101, 2651, 2003, 2183, 2000, 2022, 1037, 2204, 2154, 1012, 102, 0] 


Tokenized_batch: 
 [[101, 2651, 2003, 2183, 2000, 2022, 1037, 2204, 2154, 1012, 102, 0], [101, 1045, 3246, 2673, 2573, 2041, 1999, 2026, 5684, 999, 999, 102]]

Tensor_batch: 
 tensor([[ 101, 2651, 2003, 2183, 2000, 2022, 1037, 2204, 2154, 1012,  102,    0],
        [ 101, 1045, 3246, 2673, 2573, 2041, 1999, 2026, 5684,  999,  999,  102]])

Logits on batch: 
 SequenceClassifierOutput(loss=None, logits=tensor([[-4.2720,  4.6921],
        [-4.0785,  4.4558]], grad_fn=<AddmmBackward0>), hidden_states=None, attentions=None)

sentence 1 logits 
 tensor([[-4.2720,  4.6921]], grad_fn=<AddmmBackward0>)

sentence 2 logits 
 tensor([[-4.0785,  4.4558]], grad_fn=<AddmmBackward0>)

Batched sentence 1 & 2 logite 
 SequenceCla

{0: 'NEGATIVE', 1: 'POSITIVE'}