In [14]:
from transformers import AutoTokenizer

In [15]:
model = 'openai/gpt-oss-20b'

tokenizer = AutoTokenizer.from_pretrained(model)

raw_input = [
    "Learning about tokenizers is fun",
    "I don't like OOM errors"
]

inp = tokenizer(raw_input, padding=True, truncation=True, return_tensors='pt')
inp

Asking to truncate to max_length but no maximum length is provided and the model has no predefined maximum length. Default to no truncation.


{'input_ids': tensor([[54609,  1078,  6602, 24223,   382,  2827],
        [   40,  4128,  1299,   532,  2760, 10664]]), 'attention_mask': tensor([[1, 1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1, 1]])}

In [20]:
inp[0]

Encoding(num_tokens=6, attributes=[ids, type_ids, tokens, offsets, attention_mask, special_tokens_mask, overflowing])

In [22]:
inp = tokenizer("what is today's date?")
print(inp)
print(tokenizer.decode(inp['input_ids']))

{'input_ids': [13347, 382, 41482, 3521, 30], 'attention_mask': [1, 1, 1, 1, 1]}
what is today's date?


In [4]:
## Download pretrained model
# *Model (retrieve the hidden states)
# *ForCausalLM
# *ForMaskedLM
# *ForMultipleChoice
# *ForQuestionAnswering
# *ForSequenceClassification
# *ForTokenClassification

In [5]:
from transformers import AutoModel

In [6]:
model_card = 'openai/gpt-oss-20b'

model = AutoModel.from_pretrained(model_card, device_map='auto')

Fetching 40 files:   0%|          | 0/40 [00:00<?, ?it/s]

Loading checkpoint shards:   0%|          | 0/3 [00:00<?, ?it/s]

In [7]:
model

GptOssModel(
  (embed_tokens): Embedding(201088, 2880, padding_idx=199999)
  (layers): ModuleList(
    (0-23): 24 x GptOssDecoderLayer(
      (self_attn): GptOssAttention(
        (q_proj): Linear(in_features=2880, out_features=4096, bias=True)
        (k_proj): Linear(in_features=2880, out_features=512, bias=True)
        (v_proj): Linear(in_features=2880, out_features=512, bias=True)
        (o_proj): Linear(in_features=4096, out_features=2880, bias=True)
      )
      (mlp): GptOssMLP(
        (router): GptOssTopKRouter()
        (experts): Mxfp4GptOssExperts()
      )
      (input_layernorm): GptOssRMSNorm((2880,), eps=1e-05)
      (post_attention_layernorm): GptOssRMSNorm((2880,), eps=1e-05)
    )
  )
  (norm): GptOssRMSNorm((2880,), eps=1e-05)
  (rotary_emb): GptOssRotaryEmbedding()
)

In [11]:
out = model(**inp)
out

MoeModelOutputWithPast(last_hidden_state=tensor([[[ 1.2188e+00, -4.2500e+00,  4.1250e+00,  ..., -4.0312e+00,
           9.1250e+00, -1.8375e+01],
         [-5.1875e+00,  2.4219e+00, -1.4062e+00,  ..., -1.5469e+00,
           3.3203e-01, -1.9125e+01],
         [-8.5156e-01, -1.0703e+00,  3.8125e+00,  ...,  2.5312e+00,
           3.7188e+00, -1.9062e+00],
         [-1.5625e+00, -1.6406e+00,  3.0469e+00,  ...,  9.9219e-01,
           4.8750e+00, -1.1938e+01],
         [-8.8750e+00, -2.7148e-01, -8.4375e-01,  ..., -1.8203e+00,
           3.0312e+00,  4.0000e+00],
         [-5.4688e+00,  3.7305e-01,  3.0273e-01,  ..., -1.3281e+00,
          -1.0312e+00, -3.6250e+00]],

        [[-7.5625e+00, -3.0312e+00, -9.2578e-01,  ...,  9.6875e-01,
          -3.2344e+00, -3.4531e+00],
         [ 1.4562e+01,  4.6875e+00, -5.1953e-01,  ..., -2.6719e+00,
           2.4531e+00, -1.8281e+00],
         [-8.3125e+00,  2.9531e+00,  2.5781e+00,  ..., -4.1250e+00,
           1.9609e+00, -1.3625e+01],
         [-1

In [13]:
print(out.last_hidden_state.shape)
out.last_hidden_state

torch.Size([2, 6, 2880])


tensor([[[ 1.2188e+00, -4.2500e+00,  4.1250e+00,  ..., -4.0312e+00,
           9.1250e+00, -1.8375e+01],
         [-5.1875e+00,  2.4219e+00, -1.4062e+00,  ..., -1.5469e+00,
           3.3203e-01, -1.9125e+01],
         [-8.5156e-01, -1.0703e+00,  3.8125e+00,  ...,  2.5312e+00,
           3.7188e+00, -1.9062e+00],
         [-1.5625e+00, -1.6406e+00,  3.0469e+00,  ...,  9.9219e-01,
           4.8750e+00, -1.1938e+01],
         [-8.8750e+00, -2.7148e-01, -8.4375e-01,  ..., -1.8203e+00,
           3.0312e+00,  4.0000e+00],
         [-5.4688e+00,  3.7305e-01,  3.0273e-01,  ..., -1.3281e+00,
          -1.0312e+00, -3.6250e+00]],

        [[-7.5625e+00, -3.0312e+00, -9.2578e-01,  ...,  9.6875e-01,
          -3.2344e+00, -3.4531e+00],
         [ 1.4562e+01,  4.6875e+00, -5.1953e-01,  ..., -2.6719e+00,
           2.4531e+00, -1.8281e+00],
         [-8.3125e+00,  2.9531e+00,  2.5781e+00,  ..., -4.1250e+00,
           1.9609e+00, -1.3625e+01],
         [-1.2375e+01,  1.5137e-01,  1.1719e+00,  ...

In [16]:
out.keys()

odict_keys(['last_hidden_state', 'past_key_values'])

In [1]:
from transformers import AutoModelForSequenceClassification, AutoTokenizer

In [2]:
model_card = 'distilbert-base-uncased-finetuned-sst-2-english'

tok = AutoTokenizer.from_pretrained(model_card)

raw_input = [
    "Learning about tokenizers is fun",
    "I don't like OOM errors"
]

inp = tok(raw_input, padding=True, truncation=True, return_tensors='pt')
inp

{'input_ids': tensor([[  101,  4083,  2055, 19204, 17629,  2015,  2003,  4569,   102,     0],
        [  101,  1045,  2123,  1005,  1056,  2066,  1051,  5358, 10697,   102]]), 'attention_mask': tensor([[1, 1, 1, 1, 1, 1, 1, 1, 1, 0],
        [1, 1, 1, 1, 1, 1, 1, 1, 1, 1]])}

In [3]:
model = AutoModelForSequenceClassification.from_pretrained('distilbert-base-uncased-finetuned-sst-2-english')

out = model(**inp)

model.safetensors:   0%|          | 0.00/268M [00:00<?, ?B/s]

In [4]:
# logits (raw unnormalized scores to be converted into probability)
out

SequenceClassifierOutput(loss=None, logits=tensor([[-4.2268,  4.5430],
        [ 2.5654, -2.1671]], grad_fn=<AddmmBackward0>), hidden_states=None, attentions=None)

In [7]:
import torch

pred = torch.nn.functional.softmax(out.logits, dim=-1)
pred

tensor([[1.5533e-04, 9.9984e-01],
        [9.9127e-01, 8.7273e-03]], grad_fn=<SoftmaxBackward0>)

In [8]:
model.config.id2label

{0: 'NEGATIVE', 1: 'POSITIVE'}

In [ ]:
# First sentence: NEGATIVE: 0.0402, POSITIVE: 0.9598
# Second sentence: NEGATIVE: 0.9995, POSITIVE: 0.0005

# Models

In [9]:
from transformers import AutoModel

model = AutoModel.from_pretrained("bert-base-cased")
model

config.json:   0%|          | 0.00/570 [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/436M [00:00<?, ?B/s]

BertModel(
  (embeddings): BertEmbeddings(
    (word_embeddings): Embedding(28996, 768, padding_idx=0)
    (position_embeddings): Embedding(512, 768)
    (token_type_embeddings): Embedding(2, 768)
    (LayerNorm): LayerNorm((768,), eps=1e-12, elementwise_affine=True)
    (dropout): Dropout(p=0.1, inplace=False)
  )
  (encoder): BertEncoder(
    (layer): ModuleList(
      (0-11): 12 x BertLayer(
        (attention): BertAttention(
          (self): BertSdpaSelfAttention(
            (query): Linear(in_features=768, out_features=768, bias=True)
            (key): Linear(in_features=768, out_features=768, bias=True)
            (value): Linear(in_features=768, out_features=768, bias=True)
            (dropout): Dropout(p=0.1, inplace=False)
          )
          (output): BertSelfOutput(
            (dense): Linear(in_features=768, out_features=768, bias=True)
            (LayerNorm): LayerNorm((768,), eps=1e-12, elementwise_affine=True)
            (dropout): Dropout(p=0.1, inplace=False

In [10]:
from transformers import BertModel

model = BertModel.from_pretrained("bert-base-cased")
model

BertModel(
  (embeddings): BertEmbeddings(
    (word_embeddings): Embedding(28996, 768, padding_idx=0)
    (position_embeddings): Embedding(512, 768)
    (token_type_embeddings): Embedding(2, 768)
    (LayerNorm): LayerNorm((768,), eps=1e-12, elementwise_affine=True)
    (dropout): Dropout(p=0.1, inplace=False)
  )
  (encoder): BertEncoder(
    (layer): ModuleList(
      (0-11): 12 x BertLayer(
        (attention): BertAttention(
          (self): BertSdpaSelfAttention(
            (query): Linear(in_features=768, out_features=768, bias=True)
            (key): Linear(in_features=768, out_features=768, bias=True)
            (value): Linear(in_features=768, out_features=768, bias=True)
            (dropout): Dropout(p=0.1, inplace=False)
          )
          (output): BertSelfOutput(
            (dense): Linear(in_features=768, out_features=768, bias=True)
            (LayerNorm): LayerNorm((768,), eps=1e-12, elementwise_affine=True)
            (dropout): Dropout(p=0.1, inplace=False

In [11]:
!pwd

/app/misc


huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
	- Avoid using `tokenizers` before the fork if possible
	- Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)


## saving model weights and arch config

In [12]:
## save model weights and architecture config

model.save_pretrained('/app/misc/model_card/model.pt')

## Multiple sequence

In [23]:
import torch 
from transformers import AutoTokenizer, AutoModelForSequenceClassification

In [27]:
model_weight = "distilbert-base-uncased-finetuned-sst-2-english"

tok = AutoTokenizer.from_pretrained(model_weight)
model = AutoModelForSequenceClassification.from_pretrained(model_weight)

sequence = "I've been waiting for this course my  whole life."

tokens = tok.tokenize(sequence)
print(tokens)
ids = tok.convert_tokens_to_ids(tokens)
print(ids)

input_ids = torch.tensor([ids, ids]) ## <---
print(input_ids)

out = model(input_ids)
print(out.logits)

['i', "'", 've', 'been', 'waiting', 'for', 'this', 'course', 'my', 'whole', 'life', '.']
[1045, 1005, 2310, 2042, 3403, 2005, 2023, 2607, 2026, 2878, 2166, 1012]
tensor([[1045, 1005, 2310, 2042, 3403, 2005, 2023, 2607, 2026, 2878, 2166, 1012],
        [1045, 1005, 2310, 2042, 3403, 2005, 2023, 2607, 2026, 2878, 2166, 1012]])
tensor([[-2.7220,  2.7847],
        [-2.7220,  2.7847]], grad_fn=<AddmmBackward0>)
